[package]
name = "Keybearer"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
crypto = "0.5.1"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
serde = "1.0.219"
tokio = "1.45.1"
